{
 "title": "IP Pool",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Status Code", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "IP Overview",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(ipmanager_cooldown_list)", "legendFormat": "Banned IP" },
    { "expr": "sum(ipmanager_available_list)", "legendFormat": "Available IP" }
   ]
  },
  {
   "title": "Cooldown Condition",
   "type": "graph",
   "gridPos": { "h": 10, "w": 18, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(sum_over_time(ipmanager_cooldown_list[1h]) / 3600)",
     "legendFormat": "Average Cooldown Time"
    },
    {
     "expr": "stddev(sum_over_time(ipmanager_cooldown_list[1h]) / 3600) ",
     "legendFormat": "Stddev of Cooldown Time "
    },
    {
     "expr": "sum(ipmanager_cooldown_list) / sum(ipmanager_all_list)",
     "legendFormat": "CooldownIP / Total IP"
    }
   ]
  },
  {
   "title": "IP Burden",
   "type": "graph",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(sum(ipmanager_history_response) by (port, ip))",
     "legendFormat": "Average request got"
    },
    {
     "expr": "quantile(0.95,sum(ipmanager_history_response) by (port, ip))",
     "legendFormat": "5% heated IP request number"
    },
    {
     "expr": "max(sum(ipmanager_history_response) by (port, ip))",
     "legendFormat": "Max request of single ip"
    }
   ]
  },
  {
   "title": "Problematic IP",
   "type": "stat",
   "description": "Highest consecutive failures of IPs.",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(4, ipmanager_consecutive_failure)",
     "legendFormat": "failure of {{port}} -> {{ip}}"
    }
   ]
  },
  {
   "title": "Status code distribution",
   "type": "stat",
   "description": "Overall status code count for all ip",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ipmanager_history_response) by (status_code)"
    }
   ]
  },
  {
   "title": "Status code distribution",
   "type": "graph",
   "description": "Overall status code count for all ip",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 20 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "sum(ipmanager_history_response) by (status_code)"
    }
   ]
  }
 ]
}